# Generated by Django 6.0.5 on 2026-05-10 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30)),
                ('cidade', models.CharField(choices=[('Petrolina', 'Petrolina'), ('Juazeiro', 'Juazeiro')], max_length=20)),
                ('apelido', models.CharField(blank=True, max_length=50, null=True)),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
