# Generated by Django 6.0.5 on 2026-05-10 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cartoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('forma_pagamento', models.CharField(choices=[('Pix', 'Pix'), ('Cartão', 'Cartão'), ('Boleto', 'Boleto')], max_length=20)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovado', 'Aprovado'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=20)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartoes.cartao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
